site_name: MAutils Documentation
site_url: https://ma5951.github.io/MAutilsPro/

extra_css:
  - stylesheets/extra.css

theme:
  name : material
  favicon: assets/favicon.ico
  palette:
    scheme: slate
    primary: custom
  features:
    - navigation.path



nav:
  - Home: Pages/index.md
  - Key Features: Pages/key_features.md
  - Installation: Pages/installation.md
  - Logging: Pages/logger.md
  - Controllers: Pages/controllers.md
  - Robot Control:
      - State Machine Structure: Pages/state_machine/state_machine_structure.md
      - Subsystems:
        - Subsystems Structure: Pages/state_machine/subsystems_state_machine.md
        - State Subsystems: Pages/state_machine/state_subsystems.md
        - Subsystem States: Pages/state_machine/subsystem_states.md
        - Can Move Logic: Pages/state_machine/subsystem_logic.md
        - Subsystem Command: Pages/state_machine/subsystem_command.md
      - Robot State: Pages/state_machine/robot_state.md
      - Robot Container: 
        - Overview: Pages/state_machine/robot_container_methods.md
        - Robot State Triggers: Pages/state_machine/robot_state_triggers.md
  

  - Swerve:
      - Features And Structure: swerve/swerve.md
      - Using Swerve: swerve/swerve_drive.md
  - Subsystems:
      - Default Subsystems Structure: subsystems/default_subsystems.md
      - PowerControlledSubsystem: subsystems/power_controlled_subsystem.md
      - PositionControlledSubsystem: subsystems/position_controlled_subsystem.md
      - VelocityControlledSubsystem: subsystems/velocity_controlled_subsystem.md


markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
  