site_name: MAutils Documentation
site_url: https://mydomain.org/Home

extra_css:
  - stylesheets/extra.css

theme:
  name : material
  favicon: assets/favicon.ico
  palette:
    scheme: slate
    primary: custom
  features:
    - navigation.path



nav:
  - Home: Pages/index.md
  - Key Features: Pages/key_features.md
  - Installation: Pages/installation.md
  - Logging: Pages/logger.md
  - Controllers: Pages/controllers.md
  - State Meachine:
      - Features And Structure: Pages/state_machine/state_machine.md
      - Using State Machine: Pages/state_machine/using_state_machine.md
  - Swerve:
      - Features And Structure: swerve/swerve.md
      - Using Swerve: swerve/swerve_drive.md
  - Subsystems:
      - Deafult Subsystems Structure: subsystems/default_subsystems.md
      - PowerControlledSubsystem: subsystems/power_controlled_subsystem.md
      - PositionControlledSubsystem: subsystems/position_controlled_subsystem.md
      - VelocityControlledSubsystem: subsystems/velocity_controlled_subsystem.md


markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  
  